### ISSUE TITLE
Subscriptions playlist method no longer supported

### ISSUE THREAD

**Issue by Shamus03** [DarwinAwardWinner/download-youtube-subscriptions#3]
The method this script uses to get the list of the user's subscriptions is no longer supported, and any attempt to use the old method will yield a link to [this video](https://www.youtube.com/watch?v=UKY3scPIMd8).

For further information, see [this page](https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1).

Fortunately, `youtube-dl` already supports most of this behavior.  This script's functionality can now be mirrored in a single line using the `--download-archive` flag.  I know anyone previously using this script will be confused and won't want to take the time to fix this, so how do you feel about me making a pull request for a very large rewrite that could provide more functionality to a less experienced user?  Any options the user can change would be in a separate configuration file for them to edit, and the new version of the script would basically be less than 10 lines.

**Comment by DarwinAwardWinner** [comment]
I switched to that youtube-dl feature a while ago and no longer use this repository. I recommend you just do your development in your own fork, and I'll add a message to the README in my repo indicating that my fork is deprecated and telling people to go check out yours instead (or just use youtube-dl).

**Comment by Shamus03** [comment]
I did that.  It can be found here: https://github.com/Shamus03/download-youtube-subscriptions

**Comment by DarwinAwardWinner** [comment]
Ok, I added a README sending users to your fork.
